http:
  address:         ":8090"
  workers.command: "php-cgi worker.php"
  workers:
    pool:
      numWorkers: 10
      maxJobs:    2000

# static file serving. remove this section to disable static file serving.
static:
  # root directory for static file (http would not serve .php and .htaccess files).
  dir:   "."

  # list of extensions for forbid for serving.
  forbid: [".php", ".htaccess", ".yml"]

  always: [".ico", ".html", ".css", ".js"] 